### ISSUE TITLE
自制水印数据集

### ISSUE THREAD

**Issue by wongs19** [Kamino666/watermark-tracer#2]
哈喽作者，看了你的项目，大有收获，想在这里问下，如果我希望有其他的图片log作为水印，比如douyin之类的，在加入到图片之前应该先对彩色图片做些什么操作呢？感谢

**Comment by Kamino666** [comment]
谢谢你的支持。目录里面有一些示例的logo，和那些格式差不多就可以了，基本上就是透明背景然后大小合适。

**Comment by wongs19** [comment]
感谢回复～另外还有一个问题，我看您在训练时，num_class为2，分别是watermark和None，但数据集中好像只有watermark图片，所以这样训练的效果，和“num_class=1， watermark” 的效果等同呢？还是说我对您数据集了解有偏差？

**Comment by Kamino666** [comment]
诶呀，好像记不太清楚了，当初也不是很熟悉yolov5，好像是跟着教程来写的，这个我不太清楚，但是理论上应该是一样的吧
