### ISSUE TITLE
预测水印

### ISSUE THREAD

**Issue by zhangxiying** [Kamino666/watermark-tracer#3]
作者您好，请教个问题，在预测水印时您有一个判断假如少于等于5直接返回，大于5增强水印，麻烦讲一下这块的逻辑吧，这个增强是怎么增强的呢？

**Comment by Kamino666** [comment]
可以参考论文中3.4节所述哦

**Comment by Kamino666** [comment]
https://github.com/Kamino666/watermark-tracer/blob/master/paper/Watermark_Trace.pdf

T. Dekel, M. Rubinstein, C. Liu and W. T. Freeman, "On the Effectiveness of Visible Watermarks," 2017 IEEE Conference on Computer Vision and Pattern Recognition (CVPR), Honolulu, HI, USA, 2017, pp. 6864-6872

**Comment by zhangxiying** [comment]
感谢作者的解答，您做水印增强是为了提取出水印文字作为溯源的参数是吗

**Comment by Kamino666** [comment]
对的，不然直接出来的图有噪声干扰

**Comment by zhangxiying** [comment]
非常感谢您的解答
